# Using NumPy Library - إستخدام مكتبة نمباي

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" width="300px" alt="numpy" />

#### تحميل المكتبة :

In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
# pip install numpy
# من خلال التيرمنال الخاص بجهازك

In [6]:
import numpy as np
# التأكد من نجاح تضمين المكتبة
print("Success")

Success


In [12]:
# مصفوفة عادية
x = np.array([1, 2, 3])

# طباعة العنصر رقم 0 وهو العنصر الأول في المصفوفة
print (x[0])

1


In [14]:
y = np.array([3, 4, 5])
# تعريف مصفوفة أخرى

In [18]:
# جمع مصفوفتين

sumarrays = x+y

# الناتج مصفوفة تم جمعها بين مصفوفة اكس وواي
print(sumarrays)

[4 6 8]


In [24]:
# مصفوفة ثنائية أبعاد

a = np.array([[1, 2], [3, 4]])

In [26]:
print(a[0][1])

2


In [28]:
# مصفوفة ثلاثية الأبعاد

b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [30]:
print(b[0][1])

[3 4]


In [32]:
# ضرب المصفوفات

# تعريف المصفوفتين
a = np.array([[1, 2], [3, 4]])
c = np.array([[5, 6], [7, 8]])

In [36]:
# حفظ الضرب في متغير النتيجة وطباعته

result = np.dot(a, c)
print("Matrix multiplication result:")
print(result)

Matrix multiplication result:
[[19 22]
 [43 50]]


In [44]:
# مصفوفة صفرية

zero = np.zeros([6])

In [48]:
print(zero)
# تتكون من 6 عناصر كل عناصرها صفر

[0. 0. 0. 0. 0. 0.]


In [50]:
threedzeros = np.zeros((2, 3, 4))

# 3D Array with all elements is zeros

In [52]:
print(threedzeros)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### خاتمة الفصل

هذا الكتاب صغير جداً ويعتبر فقط مقدمة في برمجة المصفوفات ومكتبة نمباي , ولم أتطرق للعمليات المتقدمة .

نمباي مهمة جداً في البرمجة بالرياضيات وأيضاً تعديل إعدادات وأنشطة نماذج تعلم الآلة وغيرها من الإستخدامات

##### شكراً لوصولك هنا

---

### End - نهاية الفصل